development:
 adapter: postgresql
 encoding: unicode
 database: my1_development
 username: postgres
 password: 12345678
 host: localhost
 pool: 5

# production:
#   adapter: postgresql
#   encoding: unicode
#   database: myapp1_production
#   pool: 5
#   username: postgres
#   password: 12345678
#   port: 5432
#   host: localhost