# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 769957b284ec08b7e7410cc7f8cc670eec2268c7edce202d1a4a491d2752670909766e1d377a608432773374f1ef8d6787db5a8095f65403ee75f6db5c346b4a

test:
  secret_key_base: 18c67092ae8d297988bd7b638c10334783be8a36e9e88cd7b608ad7a9c0900551a01f0a1855a66e15fe09ccab14054227f711c7b9db913e40c2eb4043db63294

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
